/*
Purpose: Exact threshold test for one-dimensional rank-metric codes.
Parameters: q=3, m=6, n=6, k=1, minimum rank distance d=3.
Mathematical criterion: rk(x-lambda*g) = dim(W) + quotient tuple rank.
  WantWitness controls printing only; positive witnesses are always verified.
*/
/**********************************************************************
  check_cr_613_q3_single.m

  Exact full-tail test for one specific [6,1,3]_{3^6/3} rank-metric code.

  The code is generated by

        g = (u1,u2,u3,0,0,0),

  where u1,u2,u3 are specified in the PARAMETERS section below.

  This version:
    - uses q = 3;
    - tests exactly one chosen generator;
    - checks only subspaces W <= F_3^6 of dimension 3;
    - does not compute scalar-orbit representatives;
    - does not compute any 2-dimensional W;
    - preserves the exact ordered triple (u1,u2,u3), rather than replacing
      it with a basis chosen internally by Magma.

  IMPORTANT LOGICAL POINT:
    If a witness x is found, then d(x,C) >= 5 and hence rho(C)=5.
    If all three-spaces are exhausted without a witness, rho(C)=4.
    Indeed, any smaller tail span can be extended to a three-space;
    replacing the tail by a basis cannot decrease any distance to C.

  OPTIMIZATION FOR q=3:
    For fixed W, let B be the set of bad triples in Q^3, where Q=V/W,
    and let D be the F_3-linear subspace formed by all translation triples

       (pi(lambda*u1), pi(lambda*u2), pi(lambda*u3)), lambda in F_{3^6}.

    Instead of marking B+d for all 729 values of lambda, we quotient the
    9-dimensional space Q^3 by D and test whether the projection of B fills
    the quotient. This is exactly equivalent and is much faster.
**********************************************************************/

/**********************
   PARAMETERS
**********************/

q := 3;
m := 6;
n := 6;
d := 3;
AutoRun := true; // Edit this assignment in the file before loading.

// Print witnesses when true; always reconstruct and verify them.
WantWitness := true;

// Progress message frequency in the loop over 3-dimensional W.
ProgressStep := 100;


/**********************
   FIELDS AND VECTOR SPACES
**********************/

// Exact sphere-covering lower bound, valid also when n > m.
AuditRankCount := function(rows,cols,r)
    num := 1;
    den := 1;
    for i in [0..r-1] do
        num *:= (q^rows-q^i)*(q^cols-q^i);
        den *:= q^r-q^i;
    end for;
    return num div den;
end function;
error if q^6 * (&+[ AuditRankCount(6,6,r) : r in [0..3] ]) ge q^36,
    "Sphere-covering check failed to certify the lower bound.";
error if q ne 3 or m ne 6 or n ne 6 or d ne 3,
    "This file is specialized to the parameters in its header.";

K := GF(q);
P<t> := PolynomialRing(K);
F<a> := ext<K | t^6+t+2>;
// Powers of a use this fixed polynomial; do not change the field model.
error if Order(a) ne q^m-1, "The fixed field generator is not primitive.";
V := VectorSpace(K, m);
print "Field defining polynomial:", DefiningPolynomial(F);
error if &or[ &+[ F!(Eltseq(z)[i])*a^(i-1) : i in [1..m] ] ne z : z in F ],
    "Polynomial-coordinate conversion failed.";

T := VectorSpace(K, 9);       // coordinate model for Q^3, since dim(Q)=3

FieldElements := [ z : z in F ];
BaseFieldElements := [ z : z in K ];

// SPECIFIC REPRESENTATIVE TO TEST.
// Replace this line, for example by [ F!1, a^i, a^j ].
//GeneratorFirstThree := [ F!1, a^28, a^56 ];
//GeneratorFirstThree := [ F!1, a^282, a^117 ];
GeneratorFirstThree := [ F!1, a, a^2 ];


/**********************
   BASIC CONVERSIONS
**********************/

Vec := function(x)
    return V!Eltseq(x);
end function;

EltFromVec := function(v)
    return &+[ F!v[i] * a^(i-1) : i in [1..m] ];
end function;

RankWeight := function(L)
    return Dimension(sub< V | [ Vec(z) : z in L ] >);
end function;

DistanceToCode := function(x, g)

    dmin := m + 1;

    for lambda in FieldElements do
        y := [ x[i] - lambda*g[i] : i in [1..6] ];
        r := RankWeight(y);

        if r lt dmin then
            dmin := r;
        end if;
    end for;

    return dmin;

end function;


/**********************
   INDEXING OF FINITE VECTOR SPACES
**********************/

BaseIndex0 := function(c)
    pos := Index(BaseFieldElements, c);
    return pos - 1;
end function;

// Encode a vector by reading its coordinates as base-q digits.
VectorIndex := function(v)

    coeffs := Eltseq(v);
    idx := 1;
    pow := 1;

    for c in coeffs do
        idx +:= BaseIndex0(c) * pow;
        pow *:= q;
    end for;

    return idx;

end function;

// Inverse of VectorIndex for any finite K-vector space whose elements
// can be constructed from their coordinate sequence.
VectorFromIndex := function(X, idx)

    n := Dimension(X);
    t := idx - 1;
    coeffs := [ K | ];

    for i in [1..n] do
        digit := t mod q;
        Append(~coeffs, BaseFieldElements[digit + 1]);
        t := t div q;
    end for;

    return X!coeffs;

end function;


/**********************
   RREF DATA FOR 3-DIMENSIONAL SUBSPACES
**********************/

/*
  Each 3-dimensional subspace is generated by exactly one 3x6 matrix in
  reduced row-echelon form. We generate one W at a time during the search,
  rather than storing all 33880 subspaces in memory.
*/
FreePositionsForPivots := function(Pivots)

    FreePositions := [];

    // In row i, only non-pivot columns strictly to the right
    // of its pivot may contain free entries.
    for i in [1..3] do
        for j in [Pivots[i]+1..m] do
            if j notin Pivots then
                Append(~FreePositions, <i,j>);
            end if;
        end for;
    end for;

    return FreePositions;

end function;

NumberOfDimension3SubspacesRREF := function()

    total := 0;

    for p1 in [1..m-2] do
        for p2 in [p1+1..m-1] do
            for p3 in [p2+1..m] do
                Pivots := [ p1, p2, p3 ];
                NFree := #FreePositionsForPivots(Pivots);
                total +:= q^NFree;
            end for;
        end for;
    end for;

    return total;

end function;

BuildWFromRREFCode := function(Pivots, FreePositions, code)

    M := ZeroMatrix(K, 3, m);

    for i in [1..3] do
        M[i, Pivots[i]] := K!1;
    end for;

    t := code;

    for h in [1..#FreePositions] do
        digit := t mod q;
        i := FreePositions[h][1];
        j := FreePositions[h][2];
        M[i,j] := BaseFieldElements[digit + 1];
        t := t div q;
    end for;

    gens := [
        V![ M[i,j] : j in [1..m] ]
        : i in [1..3]
    ];

    return sub< V | gens >;

end function;


/**********************
   BAD TRIPLES FOR dim(W)=3
**********************/

/*
  For dim(W)=3, Q=V/W has dimension 3 and we need

      dim <y1,y2,y3> >= 2.

  Thus a triple is bad precisely when its span has dimension 0 or 1.
  The coordinate vectors below live in T=K^9 and are independent of W,
  so they are computed only once.
*/
BuildBadTripleVectors := function()

    Q0 := VectorSpace(K, 3);
    Q0elems := [ y : y in Q0 ];
    BadVectors := [ T | ];

    for y1 in Q0elems do
        for y2 in Q0elems do
            for y3 in Q0elems do

                if Dimension(sub< Q0 | [ y1, y2, y3 ] >) lt 2 then
                    coords := Eltseq(y1) cat Eltseq(y2) cat Eltseq(y3);
                    Append(~BadVectors, T!coords);
                end if;

            end for;
        end for;
    end for;

    return BadVectors;

end function;


/**********************
   TEST FOR ONE W OF DIMENSION 3
**********************/

FindGoodTripleForW3 := function(Uelts, W, BadVectors, WantWitness)

    u1 := Uelts[1];
    u2 := Uelts[2];
    u3 := Uelts[3];

    Q, pi := quo< V | W >;

    if Dimension(Q) ne 3 then
        error "Internal error: V/W does not have dimension 3.";
    end if;

    // D is the image of the F_3-linear map
    // lambda |-> (pi(lambda*u1),pi(lambda*u2),pi(lambda*u3)).
    // It is enough to use the polynomial basis 1,a,...,a^5 of F over K.
    Dgens := [ T | ];

    for h in [0..m-1] do

        beta := a^h;
        d1 := pi(Vec(beta*u1));
        d2 := pi(Vec(beta*u2));
        d3 := pi(Vec(beta*u3));

        coords := Eltseq(d1) cat Eltseq(d2) cat Eltseq(d3);
        Append(~Dgens, T!coords);

    end for;

    D := sub< T | Dgens >;
    S, rho := quo< T | D >;

    NClasses := #S;
    Hit := [ false : i in [1..NClasses] ];
    NumberHit := 0;

    // The union B+D fills T exactly when the projection of B fills T/D.
    for b in BadVectors do

        idx := VectorIndex(rho(b));

        if not Hit[idx] then
            Hit[idx] := true;
            NumberHit +:= 1;
        end if;

        if NumberHit eq NClasses then
            return false, [], W, Dimension(D), Dimension(S);
        end if;

    end for;

    // Choose a quotient class not hit by the bad triples.
    GoodIndex := 0;

    for idx in [1..NClasses] do
        if not Hit[idx] then
            GoodIndex := idx;
            break;
        end if;
    end for;

    if GoodIndex eq 0 then
        return false, [], W, Dimension(D), Dimension(S);
    end if;


    z := VectorFromIndex(S, GoodIndex);
    r := z @@ rho;
    rc := Eltseq(r);

    y1 := Q![ rc[i] : i in [1..3] ];
    y2 := Q![ rc[i] : i in [4..6] ];
    y3 := Q![ rc[i] : i in [7..9] ];

    v1 := y1 @@ pi;
    v2 := y2 @@ pi;
    v3 := y3 @@ pi;

    BW := Basis(W);

    x := [
        EltFromVec(v1),
        EltFromVec(v2),
        EltFromVec(v3),
        EltFromVec(BW[1]),
        EltFromVec(BW[2]),
        EltFromVec(BW[3])
    ];

    g := Uelts cat [ F!0, F!0, F!0 ];
    error if DistanceToCode(x,g) ne 5, "Independent witness verification failed.";
    return true, x, W, Dimension(D), Dimension(S);

end function;


/**********************
   SEARCH OVER ALL 3-DIMENSIONAL W, GENERATED ONE AT A TIME
**********************/

FindWitnessOverAllW3 := function(Uelts, BadVectors, WantWitness, ProgressStep)

    TotalW3 := NumberOfDimension3SubspacesRREF();
    countW := 0;

    for p1 in [1..m-2] do
        for p2 in [p1+1..m-1] do
            for p3 in [p2+1..m] do

                Pivots := [ p1, p2, p3 ];
                FreePositions := FreePositionsForPivots(Pivots);
                NFree := #FreePositions;

                for code in [0..q^NFree - 1] do

                    W := BuildWFromRREFCode(Pivots, FreePositions, code);
                    countW +:= 1;

                    if countW mod ProgressStep eq 0 then
                        print "  Checked W:", countW, "out of", TotalW3;
                    end if;

                    has5, x, Wfound, dimD, dimS :=
                        FindGoodTripleForW3(Uelts, W, BadVectors, WantWitness);

                    if has5 then
                        return true, x, Wfound, countW, TotalW3, dimD, dimS;
                    end if;

                end for;

            end for;
        end for;
    end for;

    return false, [], sub< V | [] >, countW, TotalW3, 0, 0;

end function;


/**********************
   TEST THE CHOSEN GENERATOR
**********************/

RunCustomGeneratorW3Test := procedure()

    error if ProgressStep lt 1, "ProgressStep must be positive.";
    Uelts := GeneratorFirstThree;

    print "==========================================";
    print "Exact q=3 test for one generator";
    print "q =", q;
    print "m =", m;
    print "Only subspaces W of dimension 3 are checked.";
    print "==========================================";

    if #Uelts ne 3 then
        print "ERROR: GeneratorFirstThree must contain exactly three elements.";
        return;
    end if;

    U := sub< V | [ Vec(z) : z in Uelts ] >;
    g := Uelts cat [ F!0, F!0, F!0 ];

    print "Generator:";
    print g;
    print "Rank weight / minimum distance:", RankWeight(g);

    if Dimension(U) ne 3 then
        print "ERROR: the chosen u1,u2,u3 are not F_3-linearly independent.";
        print "Their F_3-span has dimension", Dimension(U);
        return;
    end if;

    print "Precomputing the bad triples in a 3-dimensional quotient...";
    t0 := Cputime();
    BadVectors := BuildBadTripleVectors();
    print "Number of bad triples:", #BadVectors;
    print "Expected number for q=3:", 1 + 13*(q^3 - 1);
    print "Time:", Cputime(t0);

    TotalW3 := NumberOfDimension3SubspacesRREF();
    print "Number of 3-dimensional W to check:", TotalW3;
    error if TotalW3 ne 33880, "Wrong three-space count.";
    error if #BadVectors ne 339, "Wrong bad-tuple count.";

    print "Searching for a word x with d(x,C) >= 5 and dim(W)=3...";
    t1 := Cputime();

    has5, x, Wfound, countW, TotalW3, dimD, dimS :=
        FindWitnessOverAllW3(Uelts, BadVectors, WantWitness, ProgressStep);

    if has5 then

        print "==========================================";
        print "FOUND a witness using a 3-dimensional W.";
        print "Therefore d(x,C) >= 5 and rho(C) = 5.";
        print "W number:", countW, "out of", TotalW3;
        print "dim(D) =", dimD;
        print "dim(T/D) =", dimS;
        print "Subspace W:";
        print Wfound;

        if WantWitness then
            print "Witness x:";
            print x;
            print "Exact distance from x to C:";
            print DistanceToCode(x, g);
        end if;

    else

        print "==========================================";
        print "No witness was found with dim(W)=3.";
        error if countW ne TotalW3, "Incomplete negative search.";
        print "All three-spaces exhausted; the full-tail reduction is exact.";
        print "Result: rho(C) = 4 (sphere-covering lower bound).";

    end if;

    print "Search time:", Cputime(t1);
    print "==========================================";

end procedure;


/**********************
   RUN
**********************/


if AutoRun then
    RunCustomGeneratorW3Test();
end if;
