/*
Purpose: Exact threshold test for one-dimensional rank-metric codes.
Parameters: q=2, m=6, n=6, k=1, minimum rank distance d=3.
Mathematical criterion: rk(x-lambda*g) = dim(W) + quotient tuple rank.
Expected output: 22 scalar orbits with rho=4; one with rho=5.
  WantWitness controls printing only; positive witnesses are always verified.
*/
/**********************************************************************
  check_cr_613_q2.m

  Direct quotient check for [6,1,3]_{2^6/2} one-dimensional
  rank-metric codes.

  We test codes generated by

        g = (u1,u2,u3,0,0,0),     dim_F2 <u1,u2,u3> = 3.

  Goal: decide whether there exists x such that

        d(x,C) >= 5,

  i.e. RankWeight(x - lambda*g) >= 5 for every lambda in F_64.

  If such x exists, then rho(C)=5.
  If no such x exists, then rho(C)<=4; with the theoretical lower bound
  rho(C)>=4, this gives rho(C)=4.

  This baseline checks ALL 2- and 3-dimensional subspaces W <= F_2^6.
  The full-tail reduction shows that dimension 3 alone would suffice.
  Scalar-orbit reduction on W is also valid.

  Main optimization over the direct search:
  for each W we work in Q = F_2^6/W and mark the union of the bad triples.
  A good quotient triple gives a word x at distance at least 5.
**********************************************************************/

/**********************
   PARAMETERS
**********************/

q := 2;
m := 6;
n := 6;
d := 3;
AutoRun := true; // Edit this assignment in the file before loading.

// Batch parameters for the search over U representatives.
StartRep := 1;
EndRep := 0;              // 0 means: go to the last representative

// Stop as soon as a rho=4 example is found.
StopAfterFirstRho4 := false;

// Stop as soon as a rho=5 example is found.
StopAfterFirstRho5 := false;

// Print witnesses when true. Reconstruction and verification are mandatory.
WantWitness := true;

// Check W of dimension 3 first: usually faster for finding rho=5 witnesses.
CheckDimensions := [ 3, 2 ];


/**********************
   FIELDS AND VECTOR SPACE
**********************/

// Exact sphere-covering lower bound, valid also when n > m.
AuditRankCount := function(rows,cols,r)
    num := 1;
    den := 1;
    for i in [0..r-1] do
        num *:= (q^rows-q^i)*(q^cols-q^i);
        den *:= q^r-q^i;
    end for;
    return num div den;
end function;
error if q^6 * (&+[ AuditRankCount(6,6,r) : r in [0..3] ]) ge q^36,
    "Sphere-covering check failed to certify the lower bound.";
error if q ne 2 or m ne 6 or n ne 6 or d ne 3,
    "This file is specialized to the parameters in its header.";

K := GF(q);
F<a> := GF(q^m);
V := VectorSpace(K, m);
print "Field defining polynomial:", DefiningPolynomial(F);
error if &or[ &+[ F!(Eltseq(z)[i])*a^(i-1) : i in [1..m] ] ne z : z in F ],
    "Polynomial-coordinate conversion failed.";


FieldElements := [ z : z in F ];
BaseFieldElements := [ z : z in K ];


/**********************
   BASIC CONVERSIONS
**********************/

// Coordinates in the polynomial basis of F over K.

Vec := function(x)
    return V!Eltseq(x);
end function;



EltFromVec := function(v)
    return &+[ F!v[i] * a^(i-1) : i in [1..m] ];
end function;



RankWeight := function(L)
    return Dimension(sub< V | [ Vec(z) : z in L ] >);
end function;




UFromFieldElements := function(L)
    return sub< V | [ Vec(z) : z in L ] >;
end function;



BasisElements := function(U)
    return [ EltFromVec(b) : b in Basis(U) ];
end function;


/**********************
   SUBSPACE ENUMERATION
**********************/



IsInSubspaceList := function(W, L)
    for A in L do
        if A eq W then
            return true;
        end if;
    end for;
    return false;
end function;





SubspacesOfDimension := function(V, s)

    Subs := [ sub< V | [] > ];

    for d in [1..s] do

        NewSubs := [];

        for W in Subs do
            for v in V do

                if v notin W then

                    gens := [ V | ];

                    for b in Basis(W) do
                        Append(~gens, V!b);
                    end for;

                    Append(~gens, V!v);

                    X := sub< V | gens >;

                    if not IsInSubspaceList(X, NewSubs) then
                        Append(~NewSubs, X);
                    end if;

                end if;

            end for;
        end for;

        Subs := NewSubs;

    end for;

    return Subs;

end function;


/**********************
   SCALAR ACTION ON U
**********************/




MultiplySubspace := function(W, alpha)
    return sub< V | [ Vec(alpha * EltFromVec(b)) : b in Basis(W) ] >;
end function;



ScalarOrbitRepresentatives := function(SubList)

    Reps := [];
    Seen := [];

    for U in SubList do

        if not IsInSubspaceList(U, Seen) then

            Append(~Reps, U);

            for alpha in F do
                if alpha ne F!0 then
                    A := MultiplySubspace(U, alpha);
                    if not IsInSubspaceList(A, Seen) then
                        Append(~Seen, A);
                    end if;
                end if;
            end for;

        end if;

    end for;

    return Reps;

end function;


/**********************
   GENERATORS AND DISTANCES
**********************/



MakeGenerator := function(U)
    B := BasisElements(U);
    return [ B[1], B[2], B[3], F!0, F!0, F!0 ];
end function;




PrintGeneratorFromU := procedure(U)
    B := BasisElements(U);
    c := B[1]^(-1);
    Bnorm := [ c*z : z in B ];
    print [ Bnorm[1], Bnorm[2], Bnorm[3], F!0, F!0, F!0 ];
end procedure;

// All nonzero scalar multiples of a generator have the same rank weight. 

MinimumDistanceOneDim := function(g)
    return RankWeight(g);
end function;



DistanceToCode := function(x, g)

    dmin := m + 1;

    for lambda in FieldElements do
        y := [ x[i] - lambda*g[i] : i in [1..6] ];
        r := RankWeight(y);
        if r lt dmin then
            dmin := r;
        end if;
    end for;

    return dmin;

end function;


/**********************
   INDEXING IN QUOTIENT SPACES
**********************/

// Index of a base-field element in the explicitly stored enumeration.


BaseIndex0 := function(c)
    pos := Index(BaseFieldElements, c);
    return pos - 1;
end function;

// Given a vector v in a quotient vector space Q over K, encode its coordinates
// as an integer in {1,...,#Q}, using base-q digits.

VectorIndex := function(v)

    coeffs := Eltseq(v);
    idx := 1;
    pow := 1;

    for c in coeffs do
        idx +:= BaseIndex0(c) * pow;
        pow *:= q;
    end for;

    return idx;

end function;

// Bijection from Q^3 to indices 1,...,|Q|^3.

TripleIndex := function(y1, y2, y3, Qsize)
    i1 := VectorIndex(y1) - 1;
    i2 := VectorIndex(y2) - 1;
    i3 := VectorIndex(y3) - 1;
    return 1 + i1 + Qsize*i2 + Qsize^2*i3;
end function;


/**********************
   BAD TRIPLES IN Q^3
**********************/

// For a fixed quotient Q and threshold NeedDim, compute:
//   - all triples of Q^3, stored by TripleIndex;
//   - the triples whose span has dimension < NeedDim.

BuildBadTriplesData := function(Q, NeedDim)

    Qelems := [ y : y in Q ];
    Qsize := #Qelems;
    NTriples := Qsize^3;

    ZeroQ := Q!0;

    AllTriples := [* *];
    for i in [1..NTriples] do
        Append(~AllTriples, <ZeroQ, ZeroQ, ZeroQ>);
    end for;

    BadTriples := [* *];

    for y1 in Qelems do
        for y2 in Qelems do
            for y3 in Qelems do

                idx := TripleIndex(y1, y2, y3, Qsize);
                AllTriples[idx] := <y1, y2, y3>;

                S := sub< Q | [ y1, y2, y3 ] >;

                if Dimension(S) lt NeedDim then
                    Append(~BadTriples, <y1, y2, y3>);
                end if;

            end for;
        end for;
    end for;

    return Qelems, Qsize, NTriples, AllTriples, BadTriples;

end function;


/**********************
   FAST QUOTIENT TEST FOR ONE W
**********************/

// For fixed U and W, decide whether there exists a quotient triple
// (y1,y2,y3) such that for every lambda:
//
//   dim < y1-pi(lambda u1), y2-pi(lambda u2), y3-pi(lambda u3) > >= 5-dim(W).
//
// Equivalently, (y1,y2,y3) is not in the union of the translated bad triples.
FindGoodTripleForW := function(U, W, WantWitness)

    s := Dimension(W);
    NeedDim := 5 - s;

    Q, pi := quo< V | W >;
    Qelems, Qsize, NTriples, AllTriples, BadTriples := BuildBadTriplesData(Q, NeedDim);

    B := BasisElements(U);
    u1 := B[1];
    u2 := B[2];
    u3 := B[3];

    Bad := [ false : i in [1..NTriples] ];
    Marked := 0;

    for lambda in FieldElements do

        d1 := pi(Vec(lambda*u1));
        d2 := pi(Vec(lambda*u2));
        d3 := pi(Vec(lambda*u3));

        // If z=(z1,z2,z3) is bad, then y=z+(d1,d2,d3)
        // is bad for this lambda.
        for T in BadTriples do

            y1 := T[1] + d1;
            y2 := T[2] + d2;
            y3 := T[3] + d3;

            idx := TripleIndex(y1, y2, y3, Qsize);

            if not Bad[idx] then
                Bad[idx] := true;
                Marked +:= 1;
            end if;

        end for;

        // If every quotient triple is bad for at least one lambda,
        // this W cannot give a word at distance >=5.
        if Marked eq NTriples then
            return false, [], [];
        end if;

    end for;

    // We have found a quotient triple that survives all lambdas.
    for idx in [1..NTriples] do
        if not Bad[idx] then

            T := AllTriples[idx];


            v1 := T[1] @@ pi;
            v2 := T[2] @@ pi;
            v3 := T[3] @@ pi;

            BW := Basis(W);
            last := [ F | ];

            for j in [1..3] do
                if j le #BW then
                    Append(~last, EltFromVec(BW[j]));
                else
                    Append(~last, F!0);
                end if;
            end for;

            x := [ EltFromVec(v1), EltFromVec(v2), EltFromVec(v3) ] cat last;
            error if DistanceToCode(x, MakeGenerator(U)) ne 5,
                "Independent witness verification failed.";
            return true, x, W;
        end if;
    end for;

    // Should never be reached.
    return false, [], [];

end function;


/**********************
   SEARCH FOR DISTANCE >= 5
**********************/

FindDistanceAtLeast5_Hybrid := function(U, W2List, W3List, WantWitness)
    error if Seqset(CheckDimensions) ne {2,3} or #CheckDimensions ne 2,
        "CheckDimensions must contain 3 and 2 exactly once.";
    error if #W2List ne 651 or #W3List ne 1395,
        "Incomplete subspace enumeration.";

    for s in CheckDimensions do

        if s eq 2 then
            WList := W2List;
        else
            WList := W3List;
        end if;

        print "Checking all W of dimension", s;
        print "Number of W:", #WList;

        countW := 0;

        for W in WList do

            countW +:= 1;

            if countW mod 50 eq 0 then
                print "  Checked W:", countW, "out of", #WList;
            end if;

            has5, x, Wfound := FindGoodTripleForW(U, W, WantWitness);

            if has5 then
                return true, x, Wfound;
            end if;

        end for;

    end for;

    return false, [], sub< V | [] >;

end function;


/**********************
   TEST A CUSTOM GENERATOR
**********************/

TestCustomU := procedure(L)

    U := UFromFieldElements(L);

    if Dimension(U) ne 3 then
        print "The given elements do not span a 3-dimensional F_q-subspace.";
        return;
    end if;

    g := MakeGenerator(U);

    print "==========================================";
    print "Testing custom generator representative:";
    PrintGeneratorFromU(U);
    print "Minimum distance:", MinimumDistanceOneDim(g);

    print "Computing all W of dimension 2 and 3...";
    t0 := Cputime();
    W2 := SubspacesOfDimension(V, 2);
    W3 := SubspacesOfDimension(V, 3);
    print "#W2 =", #W2;
    print "#W3 =", #W3;
    print "Time:", Cputime(t0);

    print "Searching for x with d(x,C) >= 5...";
    t1 := Cputime();
    has5, x, W := FindDistanceAtLeast5_Hybrid(U, W2, W3, WantWitness);
    print "Search time:", Cputime(t1);

    if has5 then
        print "FOUND x with d(x,C) >= 5.";
        print "Therefore rho(C) = 5.";
        if WantWitness then
            print "Witness x:";
            print x;
            print "Distance from x to C:";
            print DistanceToCode(x, g);
        end if;
        print "Subspace W used:";
        print W;
    else
        print "No x with d(x,C) >= 5 was found.";
        print "Therefore rho(C) <= 4.";
        print "Using the theoretical lower bound rho(C) >= 4, rho(C) = 4.";
    end if;

    print "==========================================";

end procedure;


/**********************
   SEARCH OVER U REPRESENTATIVES
**********************/

RunSearch := procedure()

    print "==========================================";
    print "Hybrid search for [6,1,3]_{2^6/2}";
    print "q =", q;
    print "m =", m;
    print "StartRep =", StartRep;
    print "EndRep =", EndRep;
    print "CheckDimensions =", CheckDimensions;
    print "==========================================";

    print "Computing all W of dimension 2...";
    t0 := Cputime();
    W2 := SubspacesOfDimension(V, 2);
    print "#W2 =", #W2;
    print "Time:", Cputime(t0);

    print "Computing all W of dimension 3...";
    t0 := Cputime();
    W3 := SubspacesOfDimension(V, 3);
    print "#W3 =", #W3;
    print "Time:", Cputime(t0);

    print "Computing U representatives up to scalar multiplication...";
    t0 := Cputime();
    UList := ScalarOrbitRepresentatives(W3);
    print "Number of U representatives:", #UList;
    print "Time:", Cputime(t0);

    error if #UList ne 23, "Unexpected scalar-orbit count.";
    Last := #UList;
    if EndRep gt 0 then
        if EndRep lt Last then
            Last := EndRep;
        end if;
    end if;

    error if StartRep lt 1 or EndRep lt 0 or StartRep gt Last,
        "Invalid or empty batch.";
    Results := [* *];
    Found4 := false;
    Found5 := false;

    for idx in [StartRep..Last] do

        U := UList[idx];
        g := MakeGenerator(U);

        print "------------------------------------------";
        print "Candidate U number:", idx;
        print "Generator representative:";
        PrintGeneratorFromU(U);
        print "Minimum distance:", MinimumDistanceOneDim(g);

        t1 := Cputime();
        has5, x, W := FindDistanceAtLeast5_Hybrid(U, W2, W3, WantWitness);
        print "Search time:", Cputime(t1);

        if has5 then

            Append(~Results, <idx, 5>);
            Found5 := true;
            print "Result: rho(C) = 5.";
            if WantWitness then
                print "Witness x:";
                print x;
                print "Distance from x to C:";
                print DistanceToCode(x, g);
            end if;
            print "Subspace W used:";
            print W;

            if StopAfterFirstRho5 then
                print "Stopping after first rho=5 example.";
                break;
            end if;

        else

            Append(~Results, <idx, 4>);
            Found4 := true;
            print "Result: rho(C) = 4.";
            print "Example generator:";
            PrintGeneratorFromU(U);

            if StopAfterFirstRho4 then
                print "Stopping after first rho=4 example.";
                break;
            end if;

        end if;

    end for;

    print "==========================================";
    if Found4 then
        print "At least one rho=4 example was found in this batch.";
    else
        print "No rho=4 example was found in this batch.";
    end if;

    if Found5 then
        print "At least one rho=5 example was found in this batch.";
    else
        print "No rho=5 example was found in this batch.";
    end if;
    print "Completed representatives <index,rho>:", Results;
    print "rho=4:", #[R : R in Results | R[2] eq 4];
    print "rho=5:", #[R : R in Results | R[2] eq 5];
    if #Results eq #UList and StartRep eq 1 then
        print "ALL scalar-orbit representatives classified.";
    else
        print "Only the listed representatives were classified (batch/early stop).";
    end if;
    print "End of search.";
    print "==========================================";

end procedure;


/**********************
   HOW TO RUN
**********************/

// Full/batch search. Set AutoRun:=false IN THIS FILE to load functions only.
if AutoRun then
    RunSearch();
end if;
// Then, for example: TestCustomU([F!1, a^36, a^27]);
// Exponents depend on the printed defining polynomial.
